version: "3.8"

services:
  postgres:
    image: 'postgres:16.3-alpine'
    container_name: postgres_test_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - database:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
      - ./stc/test/resources/init-db.sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
volumes:
  postgres_data:
    name: postgres_test_data